# Generated by Django 5.0.6 on 2024-06-18 13:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_user_sur_name_alter_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscribe',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='subscribe', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tariff', models.PositiveSmallIntegerField(blank=True, verbose_name='Тариф')),
                ('cost', models.PositiveSmallIntegerField(blank=True, verbose_name='Цена')),
                ('status', models.PositiveSmallIntegerField(verbose_name='Статус')),
                ('date_start', models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала подписки')),
                ('date_end', models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала подписки')),
            ],
            options={
                'verbose_name': 'подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(default=0, max_length=12, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
