# Generated by Django 5.0.6 on 2024-06-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_usersubscribe_user_telephone_delete_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscribe',
            name='tariff',
            field=models.PositiveSmallIntegerField(verbose_name='Тариф'),
        ),
    ]
