# Generated by Django 5.0.6 on 2024-06-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_alter_usersubscribe_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscribe',
            name='tariff',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Тариф'),
        ),
    ]
