# Generated by Django 5.0.6 on 2024-06-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_alter_usersubscribe_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscribe',
            name='cost',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
