# Generated by Django 5.0.6 on 2024-06-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_alter_usersubscribe_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscribe',
            name='status',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Статус'),
        ),
    ]
