# Generated by Django 5.0.6 on 2024-06-20 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0009_alter_usersubscribe_cost_alter_usersubscribe_tariff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
