# Generated by Django 5.0.6 on 2024-06-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0011_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(max_length=100, unique=True, verbose_name='Телефон'),
        ),
    ]
