# Generated by Django 5.0.6 on 2024-06-22 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artobjects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsProductCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cost", models.IntegerField(verbose_name="Цена товара")),
                ("date", models.DateField(verbose_name="Дата цены")),
            ],
        ),
        migrations.CreateModel(
            name="AuthorShow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, verbose_name="Название выставки"
                    ),
                ),
                (
                    "date",
                    models.PositiveIntegerField(verbose_name="Год выставки"),
                ),
                (
                    "place",
                    models.CharField(
                        max_length=128, verbose_name="Локация выставки"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Analytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calculated_price",
                    models.IntegerField(verbose_name="Рассчитанная цена"),
                ),
                (
                    "collection",
                    models.CharField(max_length=128, verbose_name="Коллекция"),
                ),
                (
                    "media",
                    models.CharField(max_length=128, verbose_name="СМИ"),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата аналитики"
                    ),
                ),
                (
                    "art_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artobjects.product",
                    ),
                ),
                (
                    "object_author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artobjects.author",
                    ),
                ),
            ],
        ),
    ]
