# Generated by Django 5.0.6 on 2024-06-22 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("artobjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="analytics",
            name="recepient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="analyticsproductcost",
            name="analytics_result",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.analytics",
            ),
        ),
        migrations.AddField(
            model_name="authorshow",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="artobjects.author",
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="analyticsproductcost",
            name="show",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="analytics.authorshow",
            ),
        ),
    ]
