# Generated by Django 5.0.6 on 2024-06-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0003_alter_analytics_art_object_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authorshow",
            name="author",
        ),
        migrations.RemoveField(
            model_name="analytics",
            name="art_object",
        ),
        migrations.RemoveField(
            model_name="analytics",
            name="calculated_price",
        ),
        migrations.RemoveField(
            model_name="analytics",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="analytics",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="analytics",
            name="media",
        ),
        migrations.RemoveField(
            model_name="analytics",
            name="object_author",
        ),
        migrations.RemoveField(
            model_name="analytics",
            name="recepient",
        ),
        migrations.AddField(
            model_name="analytics",
            name="author_name",
            field=models.CharField(
                default="Test", max_length=128, verbose_name="Имя автора"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analytics",
            name="birth_city",
            field=models.CharField(
                default="City", max_length=128, verbose_name="Город рождения"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analytics",
            name="birth_year",
            field=models.PositiveIntegerField(
                default=2000, verbose_name="Год рождения"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analytics",
            name="category",
            field=models.CharField(
                default="Test", max_length=128, verbose_name="Катоегория"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analytics",
            name="gender",
            field=models.CharField(
                choices=[(1, "Male"), (2, "Female")],
                default=1,
                max_length=128,
                verbose_name="Пол автора",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analytics",
            name="group_show",
            field=models.CharField(
                default="Test",
                max_length=128,
                verbose_name="Групповые выставки",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analytics",
            name="height",
            field=models.PositiveIntegerField(
                default=100, verbose_name="Высота"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analytics",
            name="material",
            field=models.CharField(
                default="Test", max_length=128, verbose_name="Материал"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analytics",
            name="product_name",
            field=models.CharField(
                default="Test", max_length=128, verbose_name="Название объекта"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analytics",
            name="solo_show",
            field=models.CharField(
                default="Test",
                max_length=128,
                verbose_name="Персональные выставки",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analytics",
            name="tablet_material",
            field=models.CharField(
                default="Test",
                max_length=128,
                verbose_name="Материал планшета",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analytics",
            name="width",
            field=models.PositiveIntegerField(
                default=100, verbose_name="Ширина"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analytics",
            name="year",
            field=models.PositiveIntegerField(
                default=2000, verbose_name="Год"
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="AnalyticsProductCost",
        ),
        migrations.DeleteModel(
            name="AuthorShow",
        ),
    ]
