# Generated by Django 5.0.6 on 2024-06-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_analytics_analytics_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='height',
            field=models.FloatField(verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='width',
            field=models.FloatField(verbose_name='Ширина'),
        ),
    ]
