# Generated by Django 5.0.6 on 2024-06-18 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('year', models.PositiveIntegerField(verbose_name='Дата проведения')),
                ('place', models.CharField(max_length=50, verbose_name='Место')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Стиль',
                'verbose_name_plural': 'Стили',
            },
        ),
        migrations.CreateModel(
            name='ObjectAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=50, verbose_name='Пол')),
                ('age', models.PositiveIntegerField(null=True, verbose_name='Возраст')),
                ('year_of_birth', models.PositiveIntegerField(null=True, verbose_name='Год рождения')),
                ('city_of_birth', models.CharField(max_length=50, null=True, verbose_name='Город рождения')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='Город проживания')),
                ('education', models.CharField(max_length=50, null=True, verbose_name='Образование')),
                ('professional_education', models.CharField(max_length=50, null=True, verbose_name='Профессиональное образование')),
                ('teaching_experience', models.CharField(max_length=50, null=True, verbose_name='Опыт преподования')),
                ('socials', models.CharField(max_length=50, null=True, verbose_name='Социальные сети')),
                ('awards', models.ManyToManyField(blank=True, to='artobjects.authoraward', verbose_name='Награды автора')),
                ('personal_style', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objauthor', to='artobjects.style', verbose_name='Стиль')),
            ],
        ),
        migrations.CreateModel(
            name='ArtObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('size', models.CharField(max_length=50, verbose_name='Размер')),
                ('size_category', models.IntegerField(choices=[(1, 'SMALL'), (2, 'MEDIUM'), (3, 'LARGE')], verbose_name='Категория размера')),
                ('year', models.PositiveIntegerField(verbose_name='Год создания')),
                ('sale_city', models.CharField(max_length=50, verbose_name='Город продажи')),
                ('material', models.CharField(max_length=50, verbose_name='Материал объекта')),
                ('tablet_material', models.CharField(max_length=50, verbose_name='Материал планшета')),
                ('description', models.CharField(max_length=50, verbose_name='Описание')),
                ('cost_category', models.IntegerField(choices=[(1, 'SMALL'), (2, 'MEDIUM'), (3, 'LARGE')], verbose_name='Ценовая категория')),
                ('end_cost', models.IntegerField(verbose_name='Финальная цена')),
                ('fair_cost', models.IntegerField(verbose_name='Оценка')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликован')),
                ('category', models.ManyToManyField(to='artobjects.category', verbose_name='Категория')),
                ('genre', models.ManyToManyField(to='artobjects.genre', verbose_name='Жанр')),
                ('style', models.ManyToManyField(to='artobjects.style', verbose_name='Стиль')),
            ],
            options={
                'verbose_name': 'Артобъект',
                'verbose_name_plural': 'Артобъекты',
            },
        ),
    ]
