# Generated by Django 5.0.6 on 2024-06-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artobjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorshow',
            options={'verbose_name': 'Выставка', 'verbose_name_plural': 'Выставки'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Арт объект', 'verbose_name_plural': 'Арт объекты'},
        ),
        migrations.AlterField(
            model_name='author',
            name='city_live',
            field=models.CharField(blank=True, max_length=128, verbose_name='Город проживания'),
        ),
        migrations.AlterField(
            model_name='author',
            name='city_of_birth',
            field=models.CharField(blank=True, max_length=128, verbose_name='Город рождения'),
        ),
        migrations.AlterField(
            model_name='author',
            name='education',
            field=models.CharField(blank=True, max_length=128, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=128, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='professional_education',
            field=models.CharField(blank=True, max_length=128, verbose_name='Профессиональное образование'),
        ),
        migrations.AlterField(
            model_name='author',
            name='socials',
            field=models.CharField(blank=True, max_length=128, verbose_name='Социальные сети'),
        ),
        migrations.AlterField(
            model_name='author',
            name='teaching_experience',
            field=models.CharField(blank=True, max_length=128, verbose_name='Опыт преподования'),
        ),
        migrations.AlterField(
            model_name='authoraward',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='authorshow',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='authorshow',
            name='place',
            field=models.CharField(max_length=128, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='city_sale',
            field=models.CharField(blank=True, max_length=128, verbose_name='Город продажи'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, max_length=128, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=128, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=128, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=128, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_category',
            field=models.IntegerField(choices=[(1, 'Any'), (2, 'Small'), (3, 'Medium'), (4, 'Large'), (5, 'Oversize')], verbose_name='Категория размера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tablet_material',
            field=models.CharField(blank=True, max_length=128, verbose_name='Материал планшета'),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
    ]
