# Generated by Django 5.0.6 on 2024-06-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artobjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artobject',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='artobject',
            name='size',
            field=models.CharField(max_length=1000, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='authoraward',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='authorshow',
            name='name',
            field=models.CharField(max_length=3000, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='objectauthor',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
