# Generated by Django 5.0.6 on 2024-06-23 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artobjects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="awards",
        ),
        migrations.RemoveField(
            model_name="author",
            name="personal_style",
        ),
        migrations.RemoveField(
            model_name="author",
            name="show",
        ),
        migrations.RemoveField(
            model_name="product",
            name="author",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="product",
            name="style",
        ),
        migrations.CreateModel(
            name="ObjectAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Имя")),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[(1, "MALE"), (2, "FEMALE")],
                        max_length=128,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        null=True, verbose_name="Возраст"
                    ),
                ),
                (
                    "year_of_birth",
                    models.PositiveIntegerField(
                        blank=True, verbose_name="Год рождения"
                    ),
                ),
                (
                    "city_of_birth",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        verbose_name="Город рождения",
                    ),
                ),
                (
                    "city_live",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        verbose_name="Город проживания",
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Образование"
                    ),
                ),
                (
                    "professional_education",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        verbose_name="Профессиональное образование",
                    ),
                ),
                (
                    "teaching_experience",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        verbose_name="Опыт преподования",
                    ),
                ),
                (
                    "socials",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        verbose_name="Социальные сети",
                    ),
                ),
                (
                    "awards",
                    models.ManyToManyField(
                        blank=True,
                        to="artobjects.authoraward",
                        verbose_name="Награды автора",
                    ),
                ),
                (
                    "personal_style",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="objauthor",
                        to="artobjects.style",
                        verbose_name="Стиль",
                    ),
                ),
                (
                    "show",
                    models.ManyToManyField(
                        blank=True,
                        to="artobjects.authorshow",
                        verbose_name="Выставки автора",
                    ),
                ),
            ],
            options={
                "verbose_name": "Автор",
                "verbose_name_plural": "Авторы",
            },
        ),
        migrations.CreateModel(
            name="ArtObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, verbose_name="Название"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="", verbose_name="Изображение"
                    ),
                ),
                (
                    "additional_image",
                    models.ImageField(
                        blank=True, upload_to="", verbose_name="Изображение"
                    ),
                ),
                (
                    "size_category",
                    models.IntegerField(
                        choices=[
                            (1, "Any"),
                            (2, "Small"),
                            (3, "Medium"),
                            (4, "Large"),
                            (5, "Oversize"),
                        ],
                        verbose_name="Категория размера",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Размер"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Город"
                    ),
                ),
                (
                    "city_sale",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        verbose_name="Город продажи",
                    ),
                ),
                (
                    "year",
                    models.PositiveBigIntegerField(
                        verbose_name="Год создания"
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Материал"
                    ),
                ),
                (
                    "tablet_material",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        verbose_name="Материал планшета",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание"),
                ),
                (
                    "cost_category",
                    models.IntegerField(
                        choices=[
                            (1, "до 20 000 руб."),
                            (2, "от 20 000 до 50 000 руб."),
                            (3, "50 000 до 100 000 руб."),
                            (4, "от 100 000 до 200 000 руб."),
                            (5, "от 200 000 до 500 000 руб."),
                        ],
                        verbose_name="Ценовая категория",
                    ),
                ),
                (
                    "end_cost",
                    models.IntegerField(
                        blank=True, verbose_name="Финальная цена"
                    ),
                ),
                (
                    "fair_cost",
                    models.IntegerField(blank=True, verbose_name="Оценка"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, verbose_name="Опубликован"
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        to="artobjects.category", verbose_name="Категория"
                    ),
                ),
                (
                    "genre",
                    models.ManyToManyField(
                        to="artobjects.genre", verbose_name="Жанр"
                    ),
                ),
                (
                    "style",
                    models.ManyToManyField(
                        to="artobjects.style", verbose_name="Стиль"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atrobj",
                        to="artobjects.objectauthor",
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Арт объект",
                "verbose_name_plural": "Арт объекты",
            },
        ),
    ]
