# Generated by Django 5.0.6 on 2024-06-23 17:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0003_alter_analytics_art_object_and_more"),
        (
            "artobjects",
            "0002_remove_author_awards_remove_author_personal_style_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
